spring.application.name=finAudit-Ai


# PostgreSQL Connection Details
spring.datasource.url=jdbc:postgresql://localhost:5432/finaudit_db
spring.datasource.username=postgres
spring.datasource.password= She@123

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
